-- Populate Users table
INSERT INTO internet_store.users (login, password, role, status)
VALUES ('Admin', 'Admin123', 'Admin', 'Unblocked');

-- Populate Category table
INSERT INTO internet_store.category (category)
VALUES ('Clothes'), ('Electronic'), ('Shoes'), ('Food'), ('Households goods'), ('Books');

-- Populate Color table
INSERT INTO internet_store.color (color)
VALUES ('Black'), ('White'), ('Red'), ('Blue'), ('Green'), ('Orange'), ('Purple'), ('Brown');

-- Populate size table
INSERT INTO internet_store.size (size)
VALUES ('Not needed'), ('XS'), ('S'), ('M'), ('L'), ('XL');

-- Populate Product table
INSERT INTO internet_store.products (name, image, price, sex, category_ID, color_ID, size_ID)
VALUES ('Black T-Shirt', 'Black T-Shirt.jpg', 12, 'Male',
        (SELECT ID FROM internet_store.category WHERE category = 'Clothes'),
        (SELECT ID FROM internet_store.color WHERE color = 'Black'),
        (SELECT ID FROM internet_store.size WHERE size = 'XS')),
       ('Jeans', 'Jeans.png', 20, 'Male',
        (SELECT ID FROM internet_store.category WHERE category = 'Clothes'),
        (SELECT ID FROM internet_store.color WHERE color = 'Blue'),
        (SELECT ID FROM internet_store.size WHERE size = 'M')),
       ('Black Cap', 'BlackCap.png', 8, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Clothes'),
        (SELECT ID FROM internet_store.color WHERE color = 'Black'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('Dress', 'dress.png', 98, 'Female',
        (SELECT ID FROM internet_store.category WHERE category = 'Clothes'),
        (SELECT ID FROM internet_store.color WHERE color = 'Red'),
        (SELECT ID FROM internet_store.size WHERE size = 'S')),
       ('Coat', 'WomanCoat.jpg', 150, 'Female',
        (SELECT ID FROM internet_store.category WHERE category = 'Clothes'),
        (SELECT ID FROM internet_store.color WHERE color = 'Brown'),
        (SELECT ID FROM internet_store.size WHERE size = 'M')),
       ('Pullover', 'Pullover.png', 38, 'Male',
        (SELECT ID FROM internet_store.category WHERE category = 'Clothes'),
        (SELECT ID FROM internet_store.color WHERE color = 'White'),
        (SELECT ID FROM internet_store.size WHERE size = 'XL')),
       ('Red Hoodie', 'RedHoodie.png', 40, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Clothes'),
        (SELECT ID FROM internet_store.color WHERE color = 'Red'),
        (SELECT ID FROM internet_store.size WHERE size = 'M')),
       ('Orange Jacket', 'OrangeJacket.jpg', 400, 'Male',
        (SELECT ID FROM internet_store.category WHERE category = 'Clothes'),
        (SELECT ID FROM internet_store.color WHERE color = 'Orange'),
        (SELECT ID FROM internet_store.size WHERE size = 'M')),
       ('Glasses', 'Glasses.png', 200, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Clothes'),
        (SELECT ID FROM internet_store.color WHERE color = 'Black'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('Brown Shoes', 'BrownShoes.png', 400, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Shoes'),
        (SELECT ID FROM internet_store.color WHERE color = 'Brown'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('Red Shoes', 'RedShoes.jpg', 175, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Shoes'),
        (SELECT ID FROM internet_store.color WHERE color = 'Red'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('Airpods', 'airpods.jpg', 300, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Electronic'),
        (SELECT ID FROM internet_store.color WHERE color = 'White'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('Iphone 14', 'Iphone14.jpg', 1000, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Electronic'),
        (SELECT ID FROM internet_store.color WHERE color = 'White'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('Tv LG 14', 'LGtv.jpg', 600, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Electronic'),
        (SELECT ID FROM internet_store.color WHERE color = 'White'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('PS5', 'PS5.png', 400, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Electronic'),
        (SELECT ID FROM internet_store.color WHERE color = 'White'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('Watch', 'watch.jpg', 280, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Electronic'),
        (SELECT ID FROM internet_store.color WHERE color = 'White'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('Refrigirator', 'refrigirator.jpg', 280, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Electronic'),
        (SELECT ID FROM internet_store.color WHERE color = 'White'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('CocaCola', 'CocaCola.jpg', 30, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Food'),
        (SELECT ID FROM internet_store.color WHERE color = 'White'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('Coffee', 'coffee.jpg', 20, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Food'),
        (SELECT ID FROM internet_store.color WHERE color = 'White'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('Corona', 'Corona.jpg', 30, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Food'),
        (SELECT ID FROM internet_store.color WHERE color = 'White'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('Mivina', 'mivina.png', 1, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Food'),
        (SELECT ID FROM internet_store.color WHERE color = 'White'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('Book Green Mile', 'BookGreenMile.jpg', 14, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Books'),
        (SELECT ID FROM internet_store.color WHERE color = 'White'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('Book It', 'BookIt.jpg', 10, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Books'),
        (SELECT ID FROM internet_store.color WHERE color = 'White'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('Book Tigrolovi', 'BookTigrolovi.png', 8, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Books'),
        (SELECT ID FROM internet_store.color WHERE color = 'White'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('Kobzar Book', 'KobzarBook.jpg', 7, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Books'),
        (SELECT ID FROM internet_store.color WHERE color = 'White'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('Chair', 'Chair.jpg', 200, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Households goods'),
        (SELECT ID FROM internet_store.color WHERE color = 'White'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('Desk', 'Desk.jpg', 356, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Households goods'),
        (SELECT ID FROM internet_store.color WHERE color = 'White'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed')),
       ('Bed', 'Bed.jpg', 800, 'Unisex',
        (SELECT ID FROM internet_store.category WHERE category = 'Households goods'),
        (SELECT ID FROM internet_store.color WHERE color = 'White'),
        (SELECT ID FROM internet_store.size WHERE size = 'Not needed'));